version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: yarn
      - run: yarn test
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
